services:
  _defaults:
    autowire: true
    autoconfigure: true

  Oxodao\QneOAuthBundle\:
    resource: '../../'
    exclude:
      - '../../Controller'
      - '../../QneOauthBundle.php'
      - '../../DependencyInjection/'

  Oxodao\QneOAuthBundle\Controller\:
    resource: '../../Controller'
    public: true

  Oxodao\QneOAuthBundle\Service\:
    resource: '../../Service'
    public: true
    exclude:
      - '../../Service/TokenRoleParser/'