name: 'PR Lint'

on:
  pull_request:
    types: ['opened', 'synchronize', 'reopened', 'ready_for_review']

jobs:
  lint:
    if: 'github.event.pull_request.draft == false'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 20

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'Lint'
        env:
          CI: '1'
        run: 'make lint-ci'
